----------------------------------------------------------------------------------------------------

--#생코 실습쿼리

--CREATE TABLE - TEST_HW_AUTHOR,  TEST_HW_PROFILE,  TEST_HW_TOPIC (각ID PK설정) 

--ALTER TABLE AUTHOR ADD CONSTRAINT FK_PROFILE_ID FOREIGN KEY (PROFILE_ID) REFERENCES PROFILE(PID);
--ALTER TABLE TOPIC ADD CONSTRAINT FK_TOPIC_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AID);

--ALTER TABLE TEST_HW_PROFILE RENAME COLUMN COLUMN3 TO DESCRIPTION; (컬럼 RENAME하는방법)

--INSERT INTO PROFILE VALUES('1','developer','developer is...');
--INSERT INTO PROFILE VALUES('2','designer','designer is...');
--INSERT INTO PROFILE VALUES('3','DBA','DBA is...');
--
--INSERT INTO AUTHOR VALUES('1','lee','seoul','1');
--INSERT INTO AUTHOR VALUES('2','kim','jeju','2');
--INSERT INTO AUTHOR VALUES('3','park','busan','3');
--
--INSERT INTO TOPIC VALUES('1','HTML','html is...','1');
--INSERT INTO TOPIC VALUES('2','CSS','CSS is...','2');
--INSERT INTO TOPIC VALUES('3','Database','html is...','1');
--INSERT INTO TOPIC(tid,title,description) VALUES('4','Oracle','Oracle is...');
--commit;

-- #생코 조인 
-- [LEFT_OUTER JOIN]
--SELECT * FROM TOPIC A1 LEFT JOIN AUTHOR A2 ON A1.AUTHOR_ID=A2.AID;
--SELECT * FROM TOPIC A1 LEFT JOIN AUTHOR A2 ON A1.AUTHOR_ID = A2.AID LEFT JOIN PROFILE A3 ON A2.PROFILE_ID=A3.PID;

-- [INNER JOIN]
--SELECT * FROM TOPIC A1 INNER JOIN AUTHOR A2 ON A1.AUTHOR_ID=A2.AID;
--SELECT * FROM TOPIC A1 INNER JOIN AUTHOR A2 ON A1.AUTHOR_ID = A2.AID INNER JOIN PROFILE A3 ON A2.PROFILE_ID=A3.PID;

-- [FULL OUTER JOIN]
--SELECT * FROM TOPIC A1 FULL OUTER JOIN AUTHOR A2 ON A1.AUTHOR_ID = A2.AID;

-- [EXCLUSIVE LEFT JOIN]
--SELECT * FROM TOPIC A1 LEFT JOIN AUTHOR A2 ON A1.AUTHOR_ID = A2.AID WHERE A1.AUTHOR_ID IS NULL;

-- [CROSS JOIN]
--SELECT * FROM TOPIC A1 CROSS JOIN AUTHOR A2; 
---------------------------------------------------------------------------------------------------