--<조회년월의 급여 현황 조회(부서명칭, 사원이름순 정렬)>
SELECT A2.DEPT_NAME
     , A1.EMP_NAME
     , A3.SALARY 
  FROM TA_EMP A1
     , TA_DEPT A2
     , TA_SALARY A3 
 WHERE A1.EMP_CODE = A3.EMP_CODE 
   AND A2.DEPT_CODE = A3.DEPT_CODE
   AND A3.YYYYMM = TO_CHAR(TO_DATE('2018-03', 'YYYY-MM'), 'YYYYMM')
   ORDER BY A2.DEPT_NAME, A1.EMP_NAME;

--<조회년월의 급여 현황 및 부서별 합계 조회 (부서명칭, 사원이름순 정렬)>   
SELECT A2.DEPT_NAME
     , NVL(A1.EMP_NAME, '합계') AS EMP_NAME
     , SUM(A3.SALARY) AS SALARY
  FROM TA_EMP A1
     , TA_DEPT A2
     , TA_SALARY A3 
 WHERE A1.EMP_CODE = A3.EMP_CODE 
   AND A2.DEPT_CODE = A3.DEPT_CODE
   AND A3.YYYYMM = TO_CHAR(TO_DATE('2018-03', 'YYYY-MM'), 'YYYYMM')
   GROUP BY GROUPING SETS((A2.DEPT_NAME),(A2.DEPT_NAME, A1.EMP_NAME))
   ORDER BY A2.DEPT_NAME, A1.EMP_NAME;

--<조회년도 기준 부서별 전월/당월/전년 동월 급여를 조회>   
SELECT NVL(B1.DEPT_NAME, '합계') AS 부서
     , NVL(MAX(B1.EMP_COUNT), 			SUM(MAX(B1.EMP_COUNT)) OVER()) 			 AS 인원
     , NVL(MAX(B1.PRV_MONTH_SALARY),    SUM(MAX(B1.PRV_MONTH_SALARY)) OVER())    AS 전월
     , NVL(MAX(B1.RECENT_MONTH_SALARY), SUM(MAX(B1.RECENT_MONTH_SALARY)) OVER()) AS 당월
     , NVL(MAX(B1.PRV_YEAR_SALARY),     SUM(MAX(B1.PRV_YEAR_SALARY)) OVER())     AS 전년동월
  FROM(   
	 SELECT A2.DEPT_NAME
		  , COUNT(A1.EMP_NAME) AS EMP_COUNT
		  , DECODE(A3.YYYYMM, TO_CHAR(ADD_MONTHS(TO_DATE('2018-03', 'YYYY-MM'), -1), 'YYYYMM'),  SUM(A3.SALARY))  AS PRV_MONTH_SALARY
		  , DECODE(A3.YYYYMM, TO_CHAR(TO_DATE('2018-03', 'YYYY-MM'), 'YYYYMM'), 				 SUM(A3.SALARY))  AS RECENT_MONTH_SALARY
		  , DECODE(A3.YYYYMM, TO_CHAR(ADD_MONTHS(TO_DATE('2018-03', 'YYYY-MM'), -12), 'YYYYMM'), SUM(A3.SALARY))  AS PRV_YEAR_SALARY
	   FROM TA_EMP A1
		  , TA_DEPT A2
		  , TA_SALARY A3 
	  WHERE A1.EMP_CODE = A3.EMP_CODE 
	    AND A2.DEPT_CODE = A3.DEPT_CODE
	  GROUP BY A2.DEPT_NAME, A3.YYYYMM
	  UNION ALL
	 SELECT '' AS DEPT_NAME, NULL AS EMP_NAME, NULL AS PRV_MONTH_SALARY, NULL AS RECENT_MONTH_SALARY, NULL AS PRV_YEAR_SALARY FROM DUAL
    ) B1
GROUP BY B1.DEPT_NAME
ORDER BY B1.DEPT_NAME;
   