-- 1. 조회년월의 급여 현황 조회(부서명칭, 사원이름순 정렬)
​SELECT A1.YYYYMM, A2.DEPT_NAME, A3.EMP_NAME, A1.SALARY
  FROM TA_SALARY A1
            INNER JOIN TA_DEPT A2 ON (A1.DEPT_CODE = A2.DEPT_CODE AND A1.YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(#{SEARCH_VALUE},'YYYYMM'),-1), 'YYYYMM'))
            LEFT OUTER JOIN TA_EMP A3 ON (A1.EMP_CODE = A3.EMP_CODE )
ORDER BY A2.DEPT_NAME, A3.EMP_NAME;
​
​
--2. 조회년월의 급여 현황 및 부서별 합계 조회 (부서명칭, 사원이름순 정렬)
SELECT DECODE(A2.DEPT_NAME, NULL,'합계', A2.DEPT_NAME) AS DEPT_NAME,
          DECODE(A3.EMP_NAME, NULL,'합계', A3.EMP_NAME) AS EMP_NAME, 
          SUM(A1.SALARY) AS SALARY
 FROM TA_SALARY A1
           INNER JOIN TA_DEPT A2 ON (A1.DEPT_CODE = A2.DEPT_CODE AND A1.YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE(#{SEARCH_VALUE},'YYYYMM'),-1), 'YYYYMM'))
           LEFT OUTER JOIN TA_EMP A3 ON (A1.EMP_CODE = A3.EMP_CODE )
GROUP BY ROLLUP(A2.DEPT_NAME, A3.EMP_NAME) HAVING GROUPING_id(A2.DEPT_NAME, DEPT_NAME)IN(0,3)
ORDER BY A2.DEPT_NAME, A3.EMP_NAME;​


--3. 조회년도 기준 부서별 전월/당월/전년 동월 급여를 조회
​SELECT DECODE(A1.DEPT_NAME, NULL, '합계', A1.DEPT_NAME) AS DEPT_NAME,
          COUNT(DISTINCT A3.EMP_CODE) AS NUM,  
          SUM(DECODE(A2.YYYYMM, TO_CHAR(ADD_MONTHS(TO_DATE(#{SEARCH_VALUE},'YYYYMM'), -1), 'YYYYMM'), SALARY)) AS LAST_MONTH,
          SUM(DECODE(A2.YYYYMM, #{SEARCH_VALUE}, SALARY)) AS THIS_MONTH, 
          SUM(DECODE(A2.YYYYMM, TO_CHAR(ADD_MONTHS(TO_DATE(#{SEARCH_VALUE},'YYYYMM'), -12), 'YYYYMM'), SALARY)) AS LAST_YEAR
 FROM TA_DEPT A1, TA_SALARY A2, TA_EMP A3 
WHERE A1.DEPT_CODE = A2.DEPT_CODE
   AND A2.EMP_CODE = A3.EMP_CODE​
​GROUP BY ROLLUP(A1.DEPT_NAME) ​
ORDER BY A1.DEPT_NAME;