--1.
SELECT A1.DEPT_NAME AS "부서"
     , A2.EMP_NAME AS "이름"
     , A3.SALARY AS "급여"
  FROM TA_DEPT A1
     , TA_EMP A2
     , TA_SALARY A3
 WHERE A1.DEPT_CODE = A2.DEPT_CODE
   AND A1.DEPT_CODE = A3.DEPT_CODE
   AND A2.EMP_CODE = A3.EMP_CODE
   AND A3.YYYYMM = '201803'
 ORDER BY "부서", "이름";
 

--2.
SELECT MAX(A1.DEPT_NAME) AS "부서"
     , DECODE(A2.EMP_CODE, NULL, '합계', MAX(A2.EMP_NAME)) AS "이름"
     , SUM(A3.SALARY) AS "급여"
  FROM TA_DEPT A1
     , TA_EMP A2
     , TA_SALARY A3
 WHERE A1.DEPT_CODE = A2.DEPT_CODE
   AND A1.DEPT_CODE = A3.DEPT_CODE
   AND A2.EMP_CODE = A3.EMP_CODE
   AND A3.YYYYMM = '201803'
 GROUP BY GROUPING SETS((A1.DEPT_CODE, A2.EMP_CODE), (A1.DEPT_CODE))
 ORDER BY "부서", DECODE(A2.EMP_CODE, NULL, 1, 0), "이름";
 
--3.
SELECT B1.DEPT_NAME AS "부서"
     , EMP_CNT AS "인원"
     , PRE_MON_SAL AS "전월"
     , SAL AS "당월"
     , PRE_YEAR_SAL AS "전년동월"
  FROM ( /* 인원수 */
        SELECT NVL(A1.DEPT_CODE, 'SUM') AS DEPT_CODE
             , DECODE(A1.DEPT_CODE, NULL, '합계', MAX(A1.DEPT_NAME)) AS DEPT_NAME
             , COUNT(EMP_CODE) AS EMP_CNT  
          FROM TA_DEPT A1
             , TA_EMP A2
         WHERE A1.DEPT_CODE = A2.DEPT_CODE
         GROUP BY GROUPING SETS(A1.DEPT_CODE, ())
     ) B1
     , ( /* 급여 */
        SELECT NVL(A1.DEPT_CODE, 'SUM') AS DEPT_CODE
             , DECODE(A1.DEPT_CODE, NULL, '합계', MAX(A1.DEPT_NAME)) AS DEPT_NAME
             , SUM(DECODE(YYYYMM, TO_CHAR(ADD_MONTHS(TO_DATE('201803'||'01', 'YYYYMMDD'), -1), 'YYYYMM'), SALARY, 0)) AS PRE_MON_SAL
             , SUM(DECODE(YYYYMM, '201803', SALARY, 0)) AS SAL
             , SUM(DECODE(YYYYMM, TO_CHAR(ADD_MONTHS(TO_DATE('201803'||'01', 'YYYYMMDD'), -12), 'YYYYMM'), SALARY, 0)) AS PRE_YEAR_SAL
          FROM TA_DEPT A1
             , TA_EMP A2
             , TA_SALARY A3
         WHERE A1.DEPT_CODE = A2.DEPT_CODE
           AND A1.DEPT_CODE = A3.DEPT_CODE
           AND A2.EMP_CODE = A3.EMP_CODE
           AND (YYYYMM = '201803' 
                OR YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE('201803'||'01', 'YYYYMMDD'), -1), 'YYYYMM')
                OR YYYYMM = TO_CHAR(ADD_MONTHS(TO_DATE('201803'||'01', 'YYYYMMDD'), -12), 'YYYYMM'))
         GROUP BY GROUPING SETS(A1.DEPT_CODE, ())
     ) B2
 WHERE B1.DEPT_CODE = B2.DEPT_CODE
 ORDER BY DECODE(B1.DEPT_CODE, 'SUM', 1, 0), "부서";