--1. 조회년월의 급여 현황 조회(부서명칭, 사원이름순 정렬)
SELECT A2.DEPT_NAME AS "부서", A1.EMP_NAME AS "이름", A3.SALARY AS "급여(원)"
FROM   TA_EMP A1, TA_DEPT A2, TA_SALARY A3
WHERE  A1.DEPT_CODE = A2.DEPT_CODE
  AND  A1.EMP_CODE  = A3.EMP_CODE
  AND  A1.DEPT_CODE = A3.DEPT_CODE
  AND  A3.YYYYMM    = '201803'
ORDER BY A2.DEPT_NAME, A1.EMP_NAME;

--2. 조회년월의 급여 현황 및 부서별 합계 조회(부서명칭, 사원이름순 정렬)
SELECT A2.DEPT_NAME AS "부서", DECODE(GROUPING(A1.EMP_NAME), 1, '합계', A1.EMP_NAME) AS "이름", SUM(A3.SALARY) AS "급여(원)"
FROM   TA_EMP A1, TA_DEPT A2, TA_SALARY A3
WHERE  A1.DEPT_CODE = A2.DEPT_CODE
  AND  A1.EMP_CODE  = A3.EMP_CODE
  AND  A1.DEPT_CODE = A3.DEPT_CODE
  AND  A3.YYYYMM    = '201803'
GROUP BY ROLLUP(A2.DEPT_NAME, A1.EMP_NAME)
HAVING GROUPING(A2.DEPT_NAME) = 0
ORDER BY A2.DEPT_NAME, A1.EMP_NAME;

--3. 조회년도 기준 부서별 전월/당월/전년 동월 급여를 조회
SELECT DECODE(GROUPING(B1.DEPT_NAME), 1, '합계', B1.DEPT_NAME) AS "부서"
, COUNT(DISTINCT(B1.EMP_CODE || B1.DEPT_CODE)) AS "인원"
, SUM(DECODE(B1.YYYYMM, TO_CHAR(ADD_MONTHS(TO_DATE('201803', 'YYYYMM'), -1), 'YYYYMM'), B1.SALARY)) AS "전월급여(원)"
, SUM(DECODE(B1.YYYYMM, '201803', B1.SALARY)) AS "당월급여(원)"
, SUM(DECODE(B1.YYYYMM, TO_CHAR(ADD_MONTHS(TO_DATE('201803', 'YYYYMM'), -12), 'YYYYMM'), B1.SALARY)) AS "전년동월급여(원)"
FROM (
    SELECT A3.YYYYMM, A1.DEPT_CODE, A2.DEPT_NAME, A1.EMP_CODE, A1.EMP_NAME, A3.SALARY, A1.EMP_CODE || A1.DEPT_CODE
    FROM   TA_EMP A1, TA_DEPT A2, TA_SALARY A3
    WHERE  A1.DEPT_CODE = A2.DEPT_CODE
      AND  A1.EMP_CODE  = A3.EMP_CODE
      AND  A1.DEPT_CODE = A3.DEPT_CODE
      AND  A3.YYYYMM IN (TO_CHAR(ADD_MONTHS(TO_DATE('201803', 'YYYYMM'), -1), 'YYYYMM'), '201803', TO_CHAR(ADD_MONTHS(TO_DATE('201803', 'YYYYMM'), -12), 'YYYYMM'))
) B1
GROUP BY GROUPING SETS (B1.DEPT_NAME, ())
ORDER BY B1.DEPT_NAME;